apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choam
spec:
  rules:
    - host: choam-dev.chrispicloud.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /scalar
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /openapi
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
