apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb.yaml
  - matomo.yaml
  - grafana.yaml
  - portal.yaml
  - matomo-nginx-cm.yaml
  - matomo-config-cm.yaml
  - mariadb-init-cm.yaml
