apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
data:
  create-read-only-user.sql: |
    CREATE USER 'grafana_read'@'%' IDENTIFIED BY 'grafana';

    -- only select-rights
    GRANT SELECT ON matomo.* TO 'grafana_read'@'%';

    -- reload privileges
    FLUSH PRIVILEGES;
