apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: ghcr.io/dreyssechris/webanalysis-portal
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 200m
          volumeMounts:
            - name: fileadmin
              mountPath: /usr/share/nginx/html/fileadmin
              readOnly: true
      volumes:
        - name: fileadmin
          hostPath:
            path: /home/pi/data/bachelor-demo/fileadmin
            type: Directory
      imagePullSecrets:
        - name: ghcr-credentials
