apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: financetracker-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./deploy/k8s/apps/finance-tracker/overlays/dev
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  dependsOn:
    - name: platform
