apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/k8s/platform
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
