apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: choam-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: choam-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: bachelor-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
