apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: financetracker-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: financetracker-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: bachelor-demo
